### ISSUE TITLE
Select minor version of MySQL

### ISSUE THREAD

**Issue by YurySemchenko** [lean-delivery/ansible-role-mysql#13]
##### SUMMARY
Add description of "mysql_packages" variable to ReadMe file

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Minor version of MySQL

##### ANSIBLE VERSION

```
2.8
```

##### CONFIGURATION

MySQL 8.0

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

If we want to install specific minor version of Mysql we can change variable "mysql_packages", for example like here:

```yaml
      mysql_packages:
        - mysql-community-server-8.0.16-2.el7.x86_64
        - mysql-community-client-8.0.16-2.el7.x86_64
```
But this variable not described in Readme file

##### EXPECTED RESULTS

User will aware about selection specific version
##### ACTUAL RESULTS

Currently only latest minor version can be installed, if we not change this variable

```

```

**Comment by dzmitry-rudnouski** [comment]
Now in readme, @YurySemchenko please recheck.

**Comment by tgadiev** [comment]
.
