### ISSUE TITLE
CentOS 7.7 - OS-Specific Variables not found

### ISSUE THREAD

**Issue by stunney** [lean-delivery/ansible-role-mysql#16]
##### SUMMARY
Running playbook fails on evaluating the OS and configuration thereof.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
TASK [lean_delivery.mysql : Include OS-specific variables]

##### ANSIBLE VERSION
[vagrant@localhost ansible]$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

##### CONFIGURATION
- hosts: db-servers
  roles:
    - role: lean_delivery.mysql
  vars:
    mysql_root_password: 88TEM-veDRE<888serd
    mysql_databases:
      - name: example2_db
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: example2_user
        host: "%"
        password: Sime32-SRRR-password
        priv: "example2_db.*:ALL"
    mysql_port: 3306
    mysql_bind_address: '0.0.0.0'
    mysql_daemon: mysqld
    mysql_version: 8.0
    mysql_packages:
      - mysql-server

##### OS / ENVIRONMENT
CentOS 7.7 created from Vagrant image:

VagrantFile:
Vagrant.configure("2") do |config|

  config.vm.define "control" do |control|
    control.vm.box = "centos/7"
    
    control.vm.provider "hyperv" do |machine|
      machine.vmname = "centos7-staging"
      machine.memory = "2048"
      machine.cpus = "2"
    end

    config.vm.provision "shell",
      inline: "sudo yum -y install epel-release && yum -y update && yum -y install ansible-2.9.6"

    control.vm.synced_folder "./", "/home/vagrant/ansible", type: "rsync", rsync__exclude: ".git/"
  end
end

##### STEPS TO REPRODUCE
ansible-playbook -i ./hosts.yml webserver.yml -vvv

##### EXPECTED RESULTS
OS and daemon would be read properly and specific configuration values would be successfully loaded.

##### ACTUAL RESULTS
it fail
[vagrant@localhost ansible]$ sudo ansible-playbook -i ./hosts.yml ./webserver.yml -vvv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/vagrant/ansible/hosts.yml as it did not pass its verify_file() method
script declined parsing /home/vagrant/ansible/hosts.yml as it did not pass its verify_file() method
Parsed /home/vagrant/ansible/hosts.yml inventory source with ini plugin

PLAYBOOK: webserver.yml *********************************************************************************************************************************************************************************************************************
1 plays in ./webserver.yml

PLAY [webservers] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /home/vagrant/ansible/webserver.yml:2
<a2plvcpnl15474> ESTABLISH LOCAL CONNECTION FOR USER: root
<a2plvcpnl15474> EXEC /bin/sh -c 'echo ~root && sleep 0'
<a2plvcpnl15474> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305 `" && echo ansible-tmp-1586913327.09-172428852641305="` echo /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305 `" ) && sleep 0'
<a2plvcpnl15474> Attempting python interpreter discovery
<a2plvcpnl15474> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<a2plvcpnl15474> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<a2plvcpnl15474> PUT /root/.ansible/tmp/ansible-local-5071mv0eIu/tmpbrXQuI TO /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305/AnsiballZ_setup.py
<a2plvcpnl15474> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305/ /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305/AnsiballZ_setup.py && sleep 0'
<a2plvcpnl15474> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305/AnsiballZ_setup.py && sleep 0'
<a2plvcpnl15474> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1586913327.09-172428852641305/ > /dev/null 2>&1 && sleep 0'
ok: [a2plvcpnl15474]
META: ran handlers

TASK [lean_delivery.mysql : Include OS-specific variables] **********************************************************************************************************************************************************************************
task path: /home/vagrant/ansible/roles/lean_delivery.mysql/tasks/main.yml:3
fatal: [a2plvcpnl15474]: FAILED! => {
    "msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
a2plvcpnl15474             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by tgadiev** [comment]
Hi @stunney 

Thanks for raising the issue. It looks like your environment failed to gather correct facts. Can you add some pre_tasks to your playbook for debug purposes?

```yaml
pre_tasks:
  - name: debug ansible_os_family 
    debug:
      var: ansible_os_family

  - name: debug ansible_distribution_major_version 
    debug:
      var: ansible_distribution_major_version
```

Additionally, I would check the playbook syntax, especially indentation. Is it correct?

**Comment by stunney** [comment]
Task output is as follows:
TASK [debug ansible_os_family] *****************************************************************************************************************
task path: /home/vagrant/ansible/webserver.yml:7
ok: [a2plvcpnl15474] => {
    "ansible_os_family": "RedHat"
}

TASK [debug ansible_distribution_major_version] ************************************************************************************************
task path: /home/vagrant/ansible/webserver.yml:11
ok: [a2plvcpnl15474] => {
    "ansible_distribution_major_version": "7"
}

**Comment by tgadiev** [comment]
@stunney this way I guess that something is wrong with playbook parameters. Can you provide them in a formatted way as I did above?

I've just run test pipeline again with parameters for Mysql 8.0 and CentOS 7. It looks like the role works right:
https://gitlab.com/lean-delivery/ansible-role-mysql/-/jobs/512151716

**Comment by stunney** [comment]
Here is my directory / playbook structure (basics)
./webserver.yml (references custom role below)
./inventory_roles.yml
./roles/
-------/custom/
-------/-------/meta/main.yml (lists dependencies)
-------/-------/custom.yml (lists dependent roles, some vars)

I had all of my vars defined in the custom role as a consolidation point in the root custom.yml file.

Moving all vars to webserver.yml in the root now gets me past this issue.  Shouldn't I be able to create an aggregate role in this way and have vars defined properly?  Do I *need* to have a /custom/vars/main.yml file instead of putting vars in the custom.yml file?

**Comment by tgadiev** [comment]
@stunney I'm afraid your question is too complex. We're not aware of your environment details and the structure of the variables. Our role uses simple parameters that can be defined by a number of ways: playbook, inventory, group_vars etc. It's up to you to decide when to put your project parameters. But you just need to be sure that ansible process them correctly. You can take a look at ansible documentation for related details:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by stunney** [comment]
Thanks for the update, @tgadiev , I believe that by placing the vars in the /custom/vars/main.yml I have succeeded in getting past this hurdle for my aggregation.  I now have another issue where I don't seem to be getting the root/root user credentials stored properly.  I'll investigate further and see.  Ansible is a lot more of a pain than it seems to be worth, sadly.
