### ISSUE TITLE
Centos/RHEL 8 install adds epel and upstream mariadb repositories even though they aren't necessary

### ISSUE THREAD

**Issue by jeffcpullen** [lean-delivery/ansible-role-mysql#18]
##### SUMMARY

Adding additional repositories is not necessary on RHEL/CentOS 8, it would be nice to have an option to disable the EPEL and upstream Mariadb repositories. However the playbook adds them regardless. The only options currently (that I found) was to change the destination of the repo url / gpg key, ect. 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

RedHat

##### ANSIBLE VERSION

```
ansible 2.9.2
```

##### OS / ENVIRONMENT

RHEL 8 Clients

**Comment by tgadiev** [comment]
Hi @jeffcpullen 

Thanks for your proposal. As you correctly mentioned, currently it's possible with workaround using repo change. If you'd like to improve the role PRs are welcome!
